/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.78.0
  Forc version: 0.51.1
  Fuel-Core version: 0.22.1
*/

export type { TestContractAbi } from './TestContractAbi';

export { TestContractAbi__factory } from './factories/TestContractAbi__factory';
